debug: false
management.endpoints.web.exposure.include: "*"

logging:
  level:
    com.example.communityforum: debug
    org.springframework.web.servlet: debug
    org.hibernate.type.desriptor.sql.BasicBinder: trace


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/community_forum
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
  sql:
    init:
      mode: always

  thymeleaf3:
    decoupled-logic: true
