spring:
  datasource:
    username: root
    password: 1234
    url: jdbc:mysql://localhost:3306/community_forum?serverTimezone=UTC&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
