debug: false
management.endpoints.web.exposure.include: "*"

logging:
  level:
    com.example.communityforum: debug
    org.springframework.web.servlet: debug
    org.hibernate.type.desriptor.sql.BasicBinder: trace


spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:mysql://localhost:3306/community_forum?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: root # username과 password는 자신의 설정에 맞게
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database: mysql
    defer-datasource-initialization: true
    hibernate.ddl-auto: none
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        show_sql: true                  # 하이버네이트가 실행한 모든 SQL문을 콘솔로 출력
        format_sql: true                # SQL문을 가독성 있게 표현
        default_batch_fetch_size: 100
        use_sql_comments: true          # 디버깅 정보 출력
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  sql:
    init:
      mode: always
  data:
    rest:
      base-path: /api
      detection-strategy: annotated

---
spring:
  config.activate.on-profile: test
  datasource.url: jdbc:h2:mem:testdb
